=== kidstech/story-builder/Assets/packs/schema/pack.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "$schema": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "wordpacks": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "enabled": {
              "type": "boolean"
            },
            "nouns": {
              "$ref": "#/definitions/words"
            },
            "verbs": {
              "$ref": "#/definitions/words"
            },
            "adjectives": {
              "$ref": "#/definitions/words"
            },
            "misc": {
              "$ref": "#/definitions/words"
            }
          },
          "additionalProperties": false,
          "required": [
            "name",
            "enabled",
            "nouns",
            "verbs",
            "adjectives",
            "misc"
          ]
        },
        "additionalItems": false,
        "minItems": 1,
        "uniqueItems": true
      }
    },
    "additionalProperties": false,
    "required": [
      "name",
      "icon",
      "enabled",
      "wordpacks"
    ],
    "definitions": {
      "words": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "word": {
              "type": "string"
            },
            "forms": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "additionalItems": false,
              "uniqueItems": true
            }
          },
          "additionalProperties": false,
          "required": [
            "word",
            "forms"
          ]
        },
        "additionalItems": false,
        "minItems": 0,
        "uniqueItems": true
      }
    }
  }

=== kidstech/story-builder/Assets/packs/TestUpdatedContextPack.json
{
  "$schema": "./schema/pack.schema.json",
  "name": "Batman",
  "icon": "bat_signal.jpg",
  "enabled": true,

  "wordpacks": [
    {
      "name": "batman_villains",
      "enabled": true,
      "nouns": [
        { "word": "Joker", "forms": ["Joker"] },
        { "word": "villain", "forms": ["villain, villains"] }
      ],

      "verbs": [
        { "word": "fly", "forms": ["fly", "flown", "flew"] },
        { "word": "dance", "forms": ["dance", "danced"] },
        { "word": "steal", "forms": ["steal", "stole"] },
        { "word": "laugh", "forms": ["laugh", "laughed", "laughing"] },
        { "word": "hide", "forms": ["hide", "hid", "hiding"] }
      ],

      "adjectives": [
        { "word": "evil", "forms": ["evil"] },
        { "word": "sad", "forms": ["sad"] }
      ],

      "misc": [{ "word": "the", "forms": ["the"] }]
    },

    {
      "name": "batman_basics",
      "enabled": true,
      "nouns": [
				{ "word": "Batman", "forms": ["Batman"] },
				{ "word": "Robin", "forms": ["Robin"] }
			],

      "verbs": [
        { "word": "fly", "forms": ["fly", "flown", "flew"] },
        { "word": "dance", "forms": ["dance", "danced"] }
      ],

      "adjectives": [{ "word": "brave", "forms": ["brave"] }],
      "misc": []
    }
  ]
}

=== kidstech/story-builder/Assets/packs/farm.json
{
  "$schema": "./schema/pack.schema.json",
  "name": "farm",
  "icon": "barn.jpg",
  "enabled": true,
  "wordpacks": [
    {
      "name": "farm_animals",
      "enabled": true,
      "nouns": [
        { "word": "goat", "forms": ["goat", "goats"] },
        { "word": "sheep", "forms": ["sheep"] },
        { "word": "cat", "forms": ["cat", "cats"] },
        { "word": "dog", "forms": ["dog", "dogs"] },
        { "word": "cow", "forms": ["cow", "cows"] },
        { "word": "pig", "forms": ["pig", "pigs"] },
        { "word": "chicken", "forms": ["chicken", "chickens"] },
        { "word": "duck", "forms": ["duck", "ducks"] },
        { "word": "llama", "forms": ["llama", "llamas"] }
      ],

      "verbs": [
        { "word": "moo", "forms": ["moo", "moos", "mooed", "mooing"] },
        { "word": "oink", "forms": ["oink", "oinks", "oinked", "oinking"] },
        {
          "word": "cluck",
          "forms": ["cluck", "clucks", "clucking", "clucked"]
        },
        { "word": "baa", "forms": ["baa", "baas", "baaed", "baaing"] },
        { "word": "meow", "forms": ["meow", "meows", "meowing", "meowed"] },
        { "word": "bark", "forms": ["bark", "barks", "barked", "barking"] }
      ],

      "adjectives": [],

      "misc": []
    },

    {
      "name": "farm_equipment",
      "enabled": true,
      "nouns": [
        { "word": "harrow", "forms": ["harrow", "harrows"] },
        { "word": "tractor", "forms": ["tractor", "tractors"] },
        {
          "word": "manure spreader",
          "forms": ["manure spreader", "manure spreaders"]
        },
        { "word": "seed drill", "forms": ["seed drill", "seed drills"] },
        { "word": "baler", "forms": ["baler", "balers"] },
        { "word": "mower", "forms": ["mower", "mowers"] },
        { "word": "cultivator", "forms": ["cultivator", "cultivators"] },
        { "word": "plow", "forms": ["plow", "plows"] },
        { "word": "backhoe", "forms": ["backhoe", "backhoes"] },
        { "word": "loader", "forms": ["loader", "loaders"] },
        { "word": "sprayer", "forms": ["sprayer", "sprayers"] },
        { "word": "sickle", "forms": ["sickle", "sickles"] },
        { "word": "rake", "forms": ["rake", "rakes"] },
        { "word": "wagon", "forms": ["wagon"] },
        { "word": "trailer", "forms": ["trailer"] },
        { "word": "farm truck", "forms": ["farm truck"] },
        { "word": "hoe", "forms": ["hoe"] },
        { "word": "shovel", "forms": ["shovel"] }
      ],

      "verbs": [
        { "word": "farm", "forms": ["farm", "farms", "farmed", "farming"] },
        { "word": "grow", "forms": ["grow", "grows", "grew", "growing"] },
        { "word": "plow", "forms": ["plow", "plows", "plowing", "plowed"] }
      ],

      "adjectives": [],
      "misc": []
    }
  ]
}

=== kidstech/story-builder/Assets/packs/sightwords.json
{
  "$schema": "./schema/pack.schema.json",
  "name": "sight words",
  "icon": "eye.png",
  "enabled": true,
  "wordpacks": [
    {
      "name": "pre-k",
      "enabled": true,

      "nouns": [
        { "word": "here", "forms": ["here"] },
        { "word": "I", "forms": ["I"] },
        { "word": "it", "forms": ["it"] },
        { "word": "me", "forms": ["me"] },
        { "word": "we", "forms": ["we"] },
        { "word": "you", "forms": ["you"] }
      ],

      "verbs": [
        { "word": "can", "forms": ["can"] },
        { "word": "come", "forms": ["come", "comes", "coming"] },
        { "word": "find", "forms": ["find", "finds", "found", "finding"] },
        { "word": "go", "forms": ["go", "goes", "went", "going"] },
        { "word": "help", "forms": ["help", "helps", "helped", "helping"] },
        { "word": "is", "forms": ["is"] },
        { "word": "jump", "forms": ["jump", "jumps", "jumped", "jumping"] },
        { "word": "look", "forms": ["look", "looks", "looked", "looking"] },
        { "word": "make", "forms": ["make", "makes", "made", "making"] },
        { "word": "play", "forms": ["play", "plays", "played", "playing"] },
        { "word": "run", "forms": ["run", "runs", "ran", "running"] },
        { "word": "said", "forms": ["said"] },
        { "word": "see", "forms": ["see", "sees", "saw", "seeing"] }
      ],

      "adjectives": [
        { "word": "big", "forms": ["big"] },
        { "word": "blue", "forms": ["blue"] },
        { "word": "funny", "forms": ["funny"] },
        { "word": "little", "forms": ["little", "littler", "littlest"] },
        { "word": "my", "forms": ["my"] },
        { "word": "one", "forms": ["one"] },
        { "word": "red", "forms": ["red"] },
        { "word": "two", "forms": ["two"] },
        { "word": "three", "forms": ["three"] },
        { "word": "yellow", "forms": ["yellow"] }
      ],

      "misc": [
        { "word": "a", "forms": ["a"] },
        { "word": "and", "forms": ["and"] },
        { "word": "away", "forms": ["away"] },
        { "word": "down", "forms": ["down"] },
        { "word": "for", "forms": ["for"] },
        { "word": "in", "forms": ["in"] },
        { "word": "not", "forms": ["not"] },
        { "word": "the", "forms": ["the"] },
        { "word": "to", "forms": ["to"] },
        { "word": "up", "forms": ["up"] },
        { "word": "where", "forms": ["where"] },
        { "word": "?", "forms": ["?"] }
      ]
    },

    {
      "name": "k",
      "enabled": true,

      "nouns": [
        { "word": "he", "forms": ["he"] },
        { "word": "she", "forms": ["she"] },
        { "word": "that", "forms": ["that"] },
        { "word": "there", "forms": ["there"] },
        { "word": "they", "forms": ["they"] },
        { "word": "this", "forms": ["this"] }
      ],

      "verbs": [
        { "word": "am", "forms": ["am"] },
        { "word": "are", "forms": ["are"] },
        { "word": "ate", "forms": ["ate"] },
        { "word": "be", "forms": ["be"] },
        { "word": "came", "forms": ["came"] },
        { "word": "did", "forms": ["did"] },
        { "word": "do", "forms": ["do"] },
        { "word": "eat", "forms": ["eat", "eats", "eating"] },
        { "word": "get", "forms": ["get"] },
        { "word": "like", "forms": ["like", "likes", "liked", "liking"] },
        { "word": "must", "forms": ["must"] },
        { "word": "ran", "forms": ["ran"] },
        { "word": "ride", "forms": ["ride", "rides", "rode", "riding"] },
        { "word": "saw", "forms": ["saw"] },
        { "word": "say", "forms": ["say", "says", "saying"] },
        { "word": "want", "forms": ["want", "wants", "wanted", "wanting"] },
        { "word": "was", "forms": ["was"] },
        { "word": "went", "forms": ["went"] },
        { "word": "will", "forms": ["will"] }
      ],

      "adjectives": [
        { "word": "black", "forms": ["black"] },
        { "word": "brown", "forms": ["brown"] },
        { "word": "four", "forms": ["four"] },
        { "word": "good", "forms": ["good", "better", "best"] },
        { "word": "have", "forms": ["have"] },
        { "word": "new", "forms": ["new", "newer", "newest"] },
        { "word": "our", "forms": ["our"] },
        { "word": "pretty", "forms": ["pretty", "prettier", "prettiest"] },
        { "word": "white", "forms": ["white"] }
      ],

      "misc": [
        { "word": "all", "forms": ["all"] },
        { "word": "at", "forms": ["at"] },
        { "word": "but", "forms": ["but"] },
        { "word": "into", "forms": ["into"] },
        { "word": "no", "forms": ["no"] },
        { "word": "now", "forms": ["now"] },
        { "word": "on", "forms": ["on"] },
        { "word": "out", "forms": ["out"] },
        { "word": "please", "forms": ["please"] },
        { "word": "so", "forms": ["so"] },
        { "word": "soon", "forms": ["soon", "sooner", "soonest"] },
        { "word": "too", "forms": ["too"] },
        { "word": "under", "forms": ["under"] },
        { "word": "well", "forms": ["well"] },
        { "word": "what", "forms": ["what"] },
        { "word": "who", "forms": ["who"] },
        { "word": "with", "forms": ["with"] },
        { "word": "yes", "forms": ["yes"] }
      ]
    }
  ]
}

=== kidstech/story-builder/Assets/packs/jojo.json
{
  "$schema": "./schema/pack.schema.json",
  "name": "Jojo Siwa",
  "icon": "jojo.png",
  "enabled": true,
  "wordpacks": [
    {
      "name": "jojo",
      "enabled": true,

      "nouns": [
        { "word": "JoJo", "forms": ["JoJo"] },
        { "word": "artist", "forms": ["artist", "artists"] },
        {
          "word": "boomerang",
          "forms": ["boomerang", "boomerangs", "Boomerang"]
        },
        { "word": "bow", "forms": ["bow", "bows", "BowBow"] },
        { "word": "candy", "forms": ["candy", "candies"] },
        { "word": "competition", "forms": ["competition", "competitions"] },
        { "word": "confidence", "forms": ["confidence"] },
        { "word": "dancer", "forms": ["dancer", "dancers"] },
        { "word": "drama", "forms": ["drama"] },
        { "word": "fashion", "forms": ["fashion", "fashions"] },
        { "word": "girl", "forms": ["girl", "girls"] },
        { "word": "friendship", "forms": ["friendship"] },
        { "word": "kid", "forms": ["kid", "kids"] },
        { "word": "kiss", "forms": ["kisses"] },
        { "word": "mom", "forms": ["mom", "moms"] },
        { "word": "music", "forms": ["music"] },
        { "word": "pageant", "forms": ["pageant", "pageants"] },
        { "word": "power", "forms": ["power"] },
        { "word": "puppy", "forms": ["puppy", "puppies"] },
        { "word": "rainbow", "forms": ["rainbow", "rainbows"] },
        { "word": "show", "forms": ["show", "shows"] },
        { "word": "singer", "forms": ["singer", "singers"] },
        { "word": "song", "forms": ["song", "songs"] },
        { "word": "stage", "forms": ["stage", "stages"] },
        { "word": "store", "forms": ["store", "stores"] },
        { "word": "thing", "forms": ["thing", "things"] },
        { "word": "video", "forms": ["video", "videos"] },
        { "word": "vlog", "forms": ["vlog", "vlogs"] },
        { "word": "vlogger", "forms": ["vlogger", "vloggers"] },
        { "word": "word", "forms": ["word", "words"] }
      ],

      "verbs": [
        { "word": "dance", "forms": ["dance", "dances", "danced", "dancing"] },
        {
          "word": "dream",
          "forms": ["dream", "dreams", "dreamed", "dreaming"]
        },
        { "word": "get", "forms": ["get", "gets", "got", "getting"] },
        { "word": "hold", "forms": ["hold", "holds", "held", "holding"] },
        {
          "word": "laugh",
          "forms": ["laugh", "laughs", "laughed", "laughing"]
        },
        { "word": "like", "forms": ["like", "likes", "liked", "liking"] },
        { "word": "love", "forms": ["love", "loves", "loved", "loving"] },
        { "word": "make", "forms": ["make", "makes", "made", "making"] },
        { "word": "play", "forms": ["play", "plays", "played", "playing"] },
        {
          "word": "sing",
          "forms": ["sing", "sings", "sang", "sung", "singing"]
        },
        {
          "word": "thank",
          "forms": ["thank", "thanks", "thanked", "thanking"]
        },
        { "word": "win", "forms": ["win", "wins", "won", "winning"] }
      ],

      "adjectives": [
        { "word": "best", "forms": ["best"] },
        { "word": "colorful", "forms": ["colorful"] },
        { "word": "confident", "forms": ["confident"] },
        { "word": "dazzling", "forms": ["dazzling"] },
        { "word": "delightful", "forms": ["delightful"] },
        { "word": "exciting", "forms": ["exciting"] },
        { "word": "fun", "forms": ["fun"] },
        { "word": "good", "forms": ["good"] },
        { "word": "happy", "forms": ["happy", "happier", "happiest"] },
        { "word": "important", "forms": ["important"] },
        { "word": "impressive", "forms": ["impressive"] },
        { "word": "joyful", "forms": ["joyful"] },
        { "word": "kind", "forms": ["kind", "kindest"] },
        { "word": "posh", "forms": ["posh"] },
        { "word": "powerful", "forms": ["powerful"] },
        { "word": "sweet", "forms": ["sweet", "sweeter", "sweetest"] }
      ],

      "misc": [
        { "word": "most", "forms": ["most"] },
        { "word": "with", "forms": ["with"] },
        { "word": "her", "forms": ["her"] }
      ]
    }
  ]
}

=== kidstech/story-builder/Assets/packs/birthday.json
{
  "$schema": "./schema/pack.schema.json",
  "name": "Birthday Pack",
  "icon": "birthday.png",
  "enabled": true,

  "wordpacks": [
    {
      "name": "birthday",
      "enabled": true,

      "nouns": [
        { "word": "cake", "forms": ["cake", "cakes"] },
        { "word": "candle", "forms": ["candle", "candles"] },
        { "word": "present", "forms": ["present", "presents"] },
        { "word": "food", "forms": ["food", "foods"] },
        { "word": "piñata", "forms": ["piñata", "piñatas"] },
        { "word": "game", "forms": ["game", "games"] },
        { "word": "birthday", "forms": ["birthday"] },
        { "word": "hat", "forms": ["hat", "hats"] },
        { "word": "party", "forms": ["party", "parties"] },
        { "word": "friend", "forms": ["friend", "friends"] },
        { "word": "music", "forms": ["music"] },
        { "word": "balloon", "forms": ["balloon", "balloons"] },
        { "word": "card", "forms": ["card", "cards"] },
        { "word": "cupcake", "forms": ["cupcake", "cupcakes"] },
        { "word": "confetti", "forms": ["confetti"] },
        { "word": "candy", "forms": ["candy", "candies"] },
        { "word": "food", "forms": ["food", "foods"] },
        { "word": "ice cream", "forms": ["ice cream"] },
        { "word": "invitation", "forms": ["invitation", "invitations"] },
        { "word": "pizza", "forms": ["pizza", "pizzas"] },
        { "word": "ribbon", "forms": ["ribbon", "ribbons"] },
        { "word": "year", "forms": ["year", "years"] },
        { "word": "decoration", "forms": ["decoration", "decorations"] },
        { "word": "laughter", "forms": ["laughter"] },
        { "word": "parent", "forms": ["parent", "parents"] }
      ],

      "verbs": [
        {
          "word": "blow",
          "forms": ["blow", "blows", "blew", "blown", "blowing"]
        },
        { "word": "out", "forms": ["out"] },
        {
          "word": "celebrate",
          "forms": ["celebrate", "celebrates", "celebrated", "celebrating"]
        },
        {
          "word": "give",
          "forms": ["give", "gives", "gave", "given", "giving"]
        },
        {
          "word": "invite",
          "forms": ["invite", "invites", "invited", "inviting"]
        },
        { "word": "play", "forms": ["play", "plays", "played", "playing"] },
        {
          "word": "receive",
          "forms": ["receive", "receives", "received", "receiving"]
        },
        {
          "word": "thank",
          "forms": ["thank", "thanks", "thanked", "thanking"]
        },
        { "word": "wish", "forms": ["wish", "wishes", "wished", "wishing"] },
        { "word": "laugh", "forms": ["laugh", "laughs", "laughed", "laughing"] }
      ],

      "adjectives": [
        { "word": "fun", "forms": ["fun"] },
        { "word": "exciting", "forms": ["exciting"] },
        { "word": "happy", "forms": ["happy"] },
        { "word": "thankful", "forms": ["thankful"] },
        { "word": "colorful", "forms": ["colorful"] },
        { "word": "dazzling", "forms": ["dazzling"] },
        { "word": "delightful", "forms": ["delightful"] },
        { "word": "joyful", "forms": ["joyful"] },
        { "word": "important", "forms": ["important"] },
        { "word": "impressive", "forms": ["impressive"] }
      ],

      "misc": []
    }
  ]
}
